image: python:3.7-stretch
pipelines:
  pull-requests:
    '**':
      - step:
          name: Unit Testing
          script:
            - pip install -r requirements.txt
            - python manage.py test
